# Generated by Django 4.0.5 on 2022-06-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myuser_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='email',
            new_name='user',
        ),
    ]
