# Generated by Django 4.0.5 on 2022-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_email_myuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='test', max_length=254),
            preserve_default=False,
        ),
    ]
